import RepoPromptDomainRuntime

typealias MCPToolExecutionSettlement = RepoPromptDomainRuntime.MCPToolExecutionSettlement
typealias MCPToolExecutionCancellationOrigin = RepoPromptDomainRuntime.MCPToolExecutionCancellationOrigin
typealias MCPToolExecutionCancelledError = RepoPromptDomainRuntime.MCPToolExecutionCancelledError
typealias MCPToolExecutionWatchdogEvent = RepoPromptDomainRuntime.MCPToolExecutionWatchdogEvent
typealias MCPToolExecutionWatchdogError = RepoPromptDomainRuntime.MCPToolExecutionWatchdogError
typealias MCPToolExecutionWatchdogSchedulingPoint = RepoPromptDomainRuntime.MCPToolExecutionWatchdogSchedulingPoint
typealias MCPToolExecutionWatchdogEnvironment = RepoPromptDomainRuntime.MCPToolExecutionWatchdogEnvironment
typealias MCPToolExecutionWatchdog = RepoPromptDomainRuntime.MCPToolExecutionWatchdog
