import RepoPromptCore

// App compatibility names for the canonical Slice 1 workspace domain.
typealias WorkspacePreset = RepoPromptCore.WorkspacePreset
typealias StoredSelection = RepoPromptCore.StoredSelection
typealias ContextBuilderOverrides = RepoPromptCore.ContextBuilderOverrides
typealias ContextBuilderTabConfig = RepoPromptCore.ContextBuilderTabConfig
typealias StashedTab = RepoPromptCore.StashedTab
typealias ComposeTabState = RepoPromptCore.ComposeTabState
typealias WorkspaceModel = RepoPromptCore.WorkspaceModel
typealias CopyCustomizations = RepoPromptCore.CopyCustomizations
typealias FileTreeOption = RepoPromptCore.FileTreeOption
typealias CodeMapUsage = RepoPromptCore.CodeMapUsage
typealias GitInclusion = RepoPromptCore.GitInclusion
typealias FilesTab = RepoPromptCore.FilesTab
typealias LineRange = RepoPromptCore.LineRange
typealias WorkspaceIndexEntry = RepoPromptCore.WorkspaceIndexEntry
typealias WorkspaceSessionController = RepoPromptCore.WorkspaceSessionController
typealias WorkspaceSessionSnapshot = RepoPromptCore.WorkspaceSessionSnapshot
typealias WorkspaceSessionMutationOptions = RepoPromptCore.WorkspaceSessionMutationOptions
typealias WorkspaceSessionTransaction = RepoPromptCore.WorkspaceSessionTransaction
typealias WorkspaceSessionBindingCandidate = RepoPromptCore.WorkspaceSessionBindingCandidate
