import RepoPromptCore

// Phase 6 compatibility aliases. Resolution and accounting are Core-owned.
typealias PromptContextAccountingRequest = RepoPromptCore.PromptContextAccountingRequest
typealias PromptContextAccountingResult = RepoPromptCore.PromptContextAccountingResult
typealias PromptContextAccountingContentPolicy = RepoPromptCore.PromptContextAccountingContentPolicy
typealias PromptContextAccountingService = RepoPromptCore.PromptContextAccountingService
