import RepoPromptDomainRuntime

typealias AgentAttachmentStore = RepoPromptDomainRuntime.AgentAttachmentStore
typealias AgentSessionAttachmentStore = RepoPromptDomainRuntime.AgentSessionAttachmentStore
typealias AgentImageDropClassifier = RepoPromptDomainRuntime.AgentImageDropClassifier
typealias AgentImageDropTracker = RepoPromptDomainRuntime.AgentImageDropTracker
typealias AgentImageAttachmentGuard = RepoPromptDomainRuntime.AgentImageAttachmentGuard
typealias AgentImageAttachmentBlockReason = RepoPromptDomainRuntime.AgentImageAttachmentBlockReason
typealias AgentImageAttachmentAvailabilityResolver = RepoPromptDomainRuntime.AgentImageAttachmentAvailabilityResolver
